apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit staging
resources:
  - ../staging

# Put everything in an isolated namespace
namespace: ghost-e2e

# Distinguish object names to avoid clashes
namePrefix: e2e-

# Use the modern patch format
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ghost-ingress
    path: patch-ingress-host.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ghost
    path: patch-ghost-env-probes.yaml