apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  template:
    spec:
      containers:
      - name: ghost
        env:
          - name: url
            value: "https://example.com/blog"
          - name: admin__url
            value: "https://example.com/blog/ghost"
          - name: mail__from
            value: "admin@example.com"
          - name: mail__transport
            value: SMTP
          - name: mail__options__host
            value: smtp.your-provider.com
          - name: mail__options__port
            value: "587"
          - name: mail__options__secure
            value: "false"
          - name: mail__options__auth__user
            valueFrom:
              secretKeyRef:
                name: ghost-smtp-secret
                key: SMTP_USER
          - name: mail__options__auth__pass
            valueFrom:
              secretKeyRef:
                name: ghost-smtp-secret
                key: SMTP_PASS