apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path     # <-- keep this (matches the bound PVC)
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem