name: Validate Kustomize overlays

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.4.1"

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz \
            | tar -xz && sudo mv kubeconform /usr/local/bin/kubeconform

      - name: Validate dev overlay
        run: |
          kustomize build apps/ghost/overlays/dev \
          | kubeconform -strict -ignore-missing-schemas -summary -

      - name: Validate staging overlay
        run: |
          kustomize build apps/ghost/overlays/staging \
          | kubeconform -strict -ignore-missing-schemas -summary -

      - name: Validate prod overlay and image tags
        run: |
          tmp=$(mktemp)
          kustomize build apps/ghost/overlays/prod > "$tmp"
          if grep -E '^\s*image:\s+[^:]+:latest(\s|$)' "$tmp"; then
            echo 'Error: :latest tag found in prod overlay images' >&2
            exit 1
          fi
          kubeconform -strict -ignore-missing-schemas -summary - < "$tmp"