apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
      containers:
        - name: ghost
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      initContainers:
        - name: ghost-permissions
          image: busybox:1.36
          securityContext:
             runAsUser: 0
             runAsGroup: 0
             runAsNonRoot: false
             allowPrivilegeEscalation: false
             readOnlyRootFilesystem: true
          command: ["sh","-lc"]
          args:
            - |
              set -e
              # Ensure Ghost can create content/apps, themes, images, etc.
              chown -R 1000:1000 /var/lib/ghost/content || true
              chmod -R g+rwX /var/lib/ghost/content || true
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
